### ISSUE TITLE
[1.14.4] Mod fails to start on server due to side violation

### ISSUE THREAD

**Issue by noobanidus** [drizzs/GrassWorld-1.14#3]
```
java.lang.NoClassDefFoundError: net/minecraft/client/particle/Particle
	at com.drizzs.grassworld.particle.GrassParticleRegistry.registerParticles(GrassParticleRegistry.java:28) ~[?:2.0.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_459_GrassParticleRegistry_registerParticles_Register.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	```

**Comment by drizzs** [comment]
Will Fix
